name: readingmonitor2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  email_validator: 2.1.17
  fluttertoast: 8.0.9
  http: 0.13.4
  intl: 0.17.0
  dotted_line: 3.1.0
  syncfusion_flutter_core: 20.2.40
  syncfusion_flutter_charts: 20.2.40
  get_storage: 2.0.3
  path_provider: 2.0.11
  connectivity: 3.0.6
  shared_preferences: 2.0.15
  dropdown_search: 5.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/Icons/
  uses-material-design: true

